// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp25Ap4tlQeI-irw2fuHGxRuLJcAjeKhY',
    appId: '1:731849526877:web:6213fd7839ff4c127807b4',
    messagingSenderId: '731849526877',
    projectId: 'japaneselearningapp-ab71a',
    authDomain: 'japaneselearningapp-ab71a.firebaseapp.com',
    storageBucket: 'japaneselearningapp-ab71a.firebasestorage.app',
    measurementId: 'G-PS463BMJ62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6n1u0SKMOm-_Dh-UIypva00gO3lHjFI',
    appId: '1:731849526877:android:19cb8a5923b98dbe7807b4',
    messagingSenderId: '731849526877',
    projectId: 'japaneselearningapp-ab71a',
    storageBucket: 'japaneselearningapp-ab71a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qm684eDbZ1DSgalWvM-k7iJDbxJ2Dzw',
    appId: '1:731849526877:ios:4280620de9bc50df7807b4',
    messagingSenderId: '731849526877',
    projectId: 'japaneselearningapp-ab71a',
    storageBucket: 'japaneselearningapp-ab71a.firebasestorage.app',
    iosBundleId: 'com.antigravity.japaneseLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qm684eDbZ1DSgalWvM-k7iJDbxJ2Dzw',
    appId: '1:731849526877:ios:4280620de9bc50df7807b4',
    messagingSenderId: '731849526877',
    projectId: 'japaneselearningapp-ab71a',
    storageBucket: 'japaneselearningapp-ab71a.firebasestorage.app',
    iosBundleId: 'com.antigravity.japaneseLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp25Ap4tlQeI-irw2fuHGxRuLJcAjeKhY',
    appId: '1:731849526877:web:3928fd1fbb7aa12f7807b4',
    messagingSenderId: '731849526877',
    projectId: 'japaneselearningapp-ab71a',
    authDomain: 'japaneselearningapp-ab71a.firebaseapp.com',
    storageBucket: 'japaneselearningapp-ab71a.firebasestorage.app',
    measurementId: 'G-3BDEVGTW23',
  );
}
